CREATE TABLE IF NOT EXISTS documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(400) NOT NULL,
  chunk_count INT NOT NULL,
  created_at VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  chunk_position INT NOT NULL,
  text CLOB NOT NULL,
  CONSTRAINT fk_chunks_document FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE INDEX IF NOT EXISTS idx_chunks_document ON chunks(document_id);

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question VARCHAR(4000) NOT NULL,
  answer CLOB NOT NULL,
  mode VARCHAR(32) NOT NULL,
  created_at VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS question_citations (
  question_id BIGINT NOT NULL,
  citation_order INT NOT NULL,
  document_id BIGINT NOT NULL,
  title VARCHAR(400) NOT NULL,
  chunk_id BIGINT NOT NULL,
  chunk_position INT NOT NULL,
  text CLOB NOT NULL,
  score DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (question_id, citation_order),
  CONSTRAINT fk_citations_question FOREIGN KEY (question_id) REFERENCES questions(id)
);

CREATE INDEX IF NOT EXISTS idx_questions_created ON questions(created_at, id);
